[package]
name = "cc-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aliyun-oss-client = { version = "^0.8" }
simple_env_load = "0.2"
tracing = "0.1.29"
tracing-subscriber = "0.3.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
md5 = "0.7"