[package]
name = "cc_storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
tracing = { workspace = true }
bytesize = "1.1.0"
time = { version = "0.3", features = ["macros", "formatting", "parsing"] }
opendal = "0.30.4"
futures = "0.3"
bytes = "^1"
tokio = { version = "^1.0", features = ["fs", "io-util", "sync"] }
pin-project = "1"
crossbeam-channel = { workspace = true }
async-trait = "0.1.68"