[package]
name = "cc_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
lang-cjk = []

[dependencies]
eframe = { workspace = true }
egui = { workspace = true }