[package]
name = "cc-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc-core = { path="../cc-core" }
cc-image-cache = { path="../cc-image-cache" }
eframe = { version = "0.19.0", features = ["dark-light", "persistence"] }
egui = "0.19.0"
egui_extras = { version = "0.19.0", features = ["image"] }
image = { version = "0.24.3", default-features = false, features = ["png", "jpeg"] }
rfd = "0.10"
tokio = { version = "1", features = ["rt-multi-thread"] }
bytesize = "1.1.0"
egui-modal = "0.1"
flume = "0.10.14"
anyhow = "1.0.66"